### ISSUE TITLE
Expose current round and terminating hash?

### ISSUE THREAD

**Issue by ravener** [nvkp/crash#1]
Can we get a public field in the game to see what round we are currently on, and also get the terminating hash somehow? Isn't the concept of verifying is that users get the terminating hash and can verify it's part of the chain?

For context I'm trying to replicate something like https://bitcointalk.org/index.php?topic=5485695.0

**Comment by ravener** [comment]
Another concern is if I wanted to resume a chain, shouldn't there be a way to create a crash.Game from a given hash + maybe round number? and continue generating more hashes from it if the program restarted for example

**Comment by nvkp** [comment]
Hi, 

surely I can expose a function to return the current round number. In the post that you mentioned, the term _terminating hash_ is used for the last generated hash in the hash chain, which corresponds to the first round to be played in the game. So I can expose the hash of the first game as well. I have not exposed this fields yet, because I was supposing that it is being kept track of what round hash has been played (and therefore how many of them were there as well).

Unfortunately, one cannot revive a game simply by knowing one of the hashes. The hashes are generated in the opposite direction as the game is being played. By hashing a hash, you will get the hash of the previous game, not the next one. To revive the game, one has to know the parameters the game has been created with: the first hash in the chain, the salt, number of rounds and the instant crash rate.

**Comment by ravener** [comment]
Oh sorry, I had completely missed the fact that they are walked over backward, I thought they were generated on demand, well I guess I'll have to use a database and precache them for long chains like 10 to 100 million rounds.

Thanks.

**Comment by nvkp** [comment]
I have added two functions to the `crash.Game` struct to expose the number of so-far played rounds and the first round's hash in the release [v1.0.1](https://github.com/nvkp/crash/releases/tag/v1.0.1). What you can do for the persistance is to run the whole game and save the round hashes and the crash points into a database/file.
